import Link from 'next/link';
import type { Route } from 'next';
import AppShell from '@/components/app-shell';
import { contextoApp } from '@/lib/contexto-app';

export const dynamic = 'force-dynamic';

export default async function EquipePage() {
    const { supabase, perfil } = await contextoApp();
    const [{ data: pessoas }, { data: relatorios }, { data: conexoes }, { count: pendentes }] = await Promise.all([
        supabase.from('profiles').select('id,nome,unidade_id,status,unidades!profiles_unidade_id_fkey(nome)').eq('role','vendedor').eq('status','ativo').order('nome'),
        supabase.from('relatorios_diarios').select('user_id,data_ref,score_geral,leads_atendidos,conversoes_confirmadas,oportunidades_perdidas,tempo_medio_resposta_s,taxa_resposta').order('data_ref',{ascending:false}).limit(500),
        supabase.from('vw_conexoes_status').select('user_id,status,numero,ultimo_evento_em'),
        supabase.from('profiles').select('id',{count:'exact',head:true}).eq('status','pendente'),
    ]);
    const ultimo = new Map<string,Record<string,unknown>>(); for (const r of relatorios??[]) if(!ultimo.has(r.user_id as string)) ultimo.set(r.user_id as string,r as Record<string,unknown>);
    const cx = new Map((conexoes??[]).map(c=>[c.user_id as string,c]));
    const notas=(pessoas??[]).map(p=>Number(ultimo.get(p.id as string)?.score_geral)).filter(Number.isFinite); const media=notas.length?notas.reduce((a,b)=>a+b,0)/notas.length:null;
    return <AppShell papel={perfil.role} nome={perfil.nome} unidade={perfil.unidade} atual="/equipe"><div className="mx-auto max-w-[1180px] px-5 pb-28 pt-7 lg:px-10 lg:pb-16 lg:pt-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="display text-[30px] font-semibold">Minha equipe</h1><p className="mt-1 text-sm text-tinta-2">{pessoas?.length??0} vendedores no seu escopo</p></div>{!!pendentes&&<Link href="/aprovacoes" className="rounded-full bg-ocre-sof px-3 py-2 text-xs font-semibold text-ocre-texto">{pendentes} aprovações pendentes</Link>}</div><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-card bg-petroleo p-5 text-papel"><p className="text-xs text-white/65">Nota da equipe</p><p className="display mt-1 text-4xl font-semibold">{media==null?'—':Math.round(media)}</p></div><div className="rounded-card border border-linha bg-superficie p-5"><p className="text-xs text-tinta-2">Números fora do ar</p><p className="display mt-1 text-4xl font-semibold text-vermelho">{(pessoas??[]).filter(p=>cx.get(p.id as string)?.status!=='conectada').length}</p></div><div className="rounded-card border border-linha bg-superficie p-5"><p className="text-xs text-tinta-2">Conversões no último relatório</p><p className="display mt-1 text-4xl font-semibold">{(pessoas??[]).reduce((s,p)=>s+Number(ultimo.get(p.id as string)?.conversoes_confirmadas??0),0)}</p></div></div><section className="mt-6 overflow-hidden rounded-card border border-linha bg-superficie"><div className="grid grid-cols-[minmax(0,1fr)_80px_85px_90px] gap-3 bg-papel-2 px-4 py-3 text-[10px] font-bold uppercase tracking-wide text-tinta-3 sm:grid-cols-[minmax(0,1fr)_90px_90px_100px_100px]"><span>Vendedor</span><span>Nota</span><span>Leads</span><span>Resposta</span><span className="hidden sm:block">Conexão</span></div>{(pessoas??[]).map(p=>{const r=ultimo.get(p.id as string);const c=cx.get(p.id as string);const un=p.unidades as unknown as {nome:string}|null;return <Link href={`/equipe/${p.id}` as Route} key={p.id as string} className="grid grid-cols-[minmax(0,1fr)_80px_85px_90px] gap-3 border-t border-linha px-4 py-4 text-sm hover:bg-papel-2 sm:grid-cols-[minmax(0,1fr)_90px_90px_100px_100px]"><span><strong>{p.nome as string}</strong><small className="mt-0.5 block text-tinta-3">{un?.nome}</small></span><span className="display text-lg font-semibold">{r?.score_geral==null?'—':Math.round(Number(r.score_geral))}</span><span>{String(r?.leads_atendidos??'—')}</span><span>{r?.tempo_medio_resposta_s==null?'—':`${Math.round(Number(r.tempo_medio_resposta_s)/60)} min`}</span><span className={`hidden text-xs font-semibold sm:block ${c?.status==='conectada'?'text-verde':'text-vermelho'}`}>{c?.status??'sem conexão'}</span></Link>})}</section></div></AppShell>;
}
